hostname = *.xiaohongshu.com


^https?:\/\/[a-z]+\.xiaohongshu\.com\/api\/sns\/v\d+\/homefeed\? url script-response-body https://raw.githubusercontent.com/ddgksf2013/dev/35b6c84e448c3ac7cf176f40cc949635c9f64667/redbook_json.js
