##############################################
# > 如需引用请注明出处，谢谢合作！
# > https://t.me/ddgksf2021
# > Only for own use, created by ddgksf2013
# > 更新时间：2025-05-05
# > APP解锁状态说明如下
# > 已验证✅ 待验证🟨 已失效🟥
# > https://github.com/ddgksf2013/dev/raw/master/ForOwnUse.conf
##############################################

hostname = ipadcms.caixin.com




#>>>>>>>>>>>>>>>>新闻类VIP
# ✅ 财新周刊
http://ipadcms.caixin.com/tmp/articles url script-response-body https://github.com/ddgksf2013/dev/raw/main/CaiXinZhouKanProCrack.js
